server:
  port: 10001
  #  配置上下文（项目路径），改变项目URL资源定位
  servlet:
    context-path: /user
#  http://localhost:10001/user/
spring:
  # 定义匹配静态资源路径
  mvc:
    static-path-pattern: /**
  # 定义静态资源位置
  #  resources:
  #    static-locations:
  #      classpath: /META-INF/resources/,/resources/,/static/,/public/
  #当遇到同样名字的时候，是否允许覆盖注册
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/homepage?useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2B8
    username: root
    password: root
  redis:
    port: 6379
    # Redis服务器地址
    host: 127.0.0.1
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接密码（默认为空）
    password:
    # 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1ms
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 5000ms
    # 缓存配置顺序 Redis使用有影响**（JCache -> EhCache -> Redis -> Guava）**
    # 一般来说是不用配置的，Spring Cache 会根据依赖的包自行装配

#  cache:
#    type: redis
#    redis:
#    #      Redis默认情况下有16个分片，这里配置具体使用的分片
#    database: 0
#    host: 127.0.0.1
#    port: 6379
#    password: tyyz@2020!!up
#    #      连接超时时间（毫秒）
#    timeout: 3000ms
#    lettuce:
#      pool:
#    #      连接池最大连接数（使用负值表示没有限制） 默认 8
#    max-active: 200
#    #      连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
#    max-wait: 3000ms
#    #    连接池中的最大空闲连接 默认 8
#    max-idle: 150
#    #    连接池中的最小空闲连接 默认 0
#    min-idle: 50
#    lock:
#      waitTimeOut: 5
#      lockTimeOut: 10
##    redis在yml文件的配置
# Redis服务器连接端口


#定义有封装化类
encryption:
  MD5KEY: weige

file:
  uploadDefaultPath: D:/WeiGe